### ISSUE TITLE
Loading the reference of legacy model file fails

### ISSUE THREAD

**Issue by livia-b** [statismo/statismo#213]
Loading the reference of legacy model file fails because the reader doesn't recognize the file format.
The problem is that the reference is saved in a file without extension (in LoadRefLegacy statismo::Utils::CreateTmpName(".vtk") )

**Comment by marcelluethi** [comment]
Thanks for reporting. A fix is on the way.

**Comment by marcelluethi** [comment]
@livia-b Commit e58d23e  fixes the problem for me. Can you quickly check that it works for you?

**Comment by livia-b** [comment]
@marcelluethi I've tried with statismo-sample on a file that was giving the problem before, now it works, thanks!
