### ISSUE TITLE
Superbuild fails on Windows due to boost

### ISSUE THREAD

**Issue by dzenanz** [statismo/statismo#224]
The relevant excerpt from the build log is below. I am using VS2013 x64 generator.
```
7>  CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.4/Modules/FindBoost.cmake:1247 (message):
7>    Unable to find the requested Boost libraries.
7>  
7>    Boost version: 1.56.0
7>  
7>    Boost include path: C:/Misc/statismo-superbuild2/INSTALL/include/boost-1_56
7>  
7>    Could not find the following static Boost libraries:
7>  
7>            boost_thread
7>            boost_system
7>            boost_date_time
7>            boost_filesystem
7>            boost_program_options
7>  
7>    No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
7>    directory containing Boost libraries or BOOST_ROOT to the location of
7>    Boost.
7>  Call Stack (most recent call first):
7>    CMakeLists.txt:113 (find_package)
```

**Comment by marcelluethi** [comment]
A similar issue was recently reported on the mailing list:
https://groups.google.com/forum/#!msg/statismo-users/u_eHbCn5UcA/Qcsl2eQdMBgJ

The problem was due to several different boost version that were installed on the system. 
Can you check if the instructions given there work for you?

Thanks,  

Marcel

**Comment by dzenanz** [comment]
Manually setting Boost_THREAD_LIBRARY etc gets rid of that CMake error, but now results in errors such as these:
```
Error	18	error LNK2038: mismatch detected for '_MSC_VER': value '1900' doesn't match value '1800' in ITKHeaderTest4.obj	C:\Misc\statismo-superbuild2\Statismo-build\modules\ITK\libboost_thread-vc140-mt-gd-1_56.lib(thread.obj)
Error	22	error LNK2005: "public: __cdecl std::_Container_base12::_Container_base12(void)" (??0_Container_base12@std@@QEAA@XZ) already defined in libboost_thread-vc140-mt-gd-1_56.lib(thread.obj)	C:\Misc\statismo-superbuild2\Statismo-build\modules\ITK\msvcprtd.lib(MSVCP120D.dll)
Error	26	error LNK1104: cannot open file 'libboost_filesystem-vc120-mt-gd-1_56.lib'	C:\Misc\statismo-superbuild2\Statismo-build\modules\ITK\LINK
```
It is obvious that VS2015 got used to build boost instead of VS2013. I had the same problem when I built boost manually on Monday (not part of superbuild). `toolset=msvc-12.0 address-model=64` needed to be specified when invoking `b2`. I see that address model is set in `Boost_b2_Command` in `External-Boost.cmake`. Is there something more elegant for toolset than a big if/else statemant regarding [version numbers](https://cmake.org/cmake/help/v3.4/variable/MSVC_VERSION.html)?

**Comment by marcelluethi** [comment]
Did I understand you correctly that you know how to solve the issue? 
Unfortunately I am now a windows developer and cannot help you much with this issue. We are currently lacking a bit Windows expertise on the statismo developers side.  If you post the question on  the statismo mailing list you might have more luck, as there are quite a few people using statismo on windows.

**Comment by dzenanz** [comment]
Adding `--toolset=msvc-12.0` on line 38 of `External-Boost.cmake` solved the issue with a clean build (did not work with existing build). I am now testing a more general solution for different versions of Visual Studio.

**Comment by dzenanz** [comment]
https://github.com/statismo/statismo/pull/229
