### ISSUE TITLE
develop branch: (sample size) >= (3* number of coordinates ) gives wrong variance

### ISSUE THREAD

**Issue by zarquon42b** [statismo/statismo#239]
With the merge of  5c5a05fee23979b27dc1a86ecbaea7b9760d0f7e (@tom-albrecht introduced the memory efficient PCA), the PCA calculation gives wrong results if (sample size) >= (3* coordinate size) - e.g with large set of individuals but sparse point clouds.

**Comment by tom-albrecht** [comment]
That sounds like the case “large n, small p”, in which the data matrix has more columns than rows. 

Maybe I did not properly consider this case in the fix. I can have a look if I find my mistake. 

 

Of course I don’t mind if anyone quicker fixes it.

**Comment by tom-albrecht** [comment]
I just took a closer look. This case should take you to the `else `case in **PCAModelBuilder.h:195**, which I never changed.
Can you investigate if you do end up in that `else `case and check what may be going wrong?

**Comment by zarquon42b** [comment]
Hi, I am already investigating.

to confirm that this merge must be a culprit, I compared results from
before and after this commit.

Best
Stefan

**Comment by tom-albrecht** [comment]
That can't really be the case, because the very commit you marked only removed a second superfluous computing of the scores. 

It must be a larger change, and what you marked was just the very last commit of that change.

**Comment by zarquon42b** [comment]
To be more precise, I compared

6afdf8a48d3ddab946506b677c2c6397e8c7a8e1 Merge pull request #226 from
tom-albrecht/memory-optimization-PCA

to

b1a69864e1fcc51aa022a0404c7b5e06a8f63e67     added 4d and unsigned traits

But maybe I am wrong
Attached you find the diff

Best
Stefan

**Comment by tom-albrecht** [comment]
OK. That makes more sense. 

So you get a wrong variance (= eigenvalues), but correct eigenvectors?
What's wrong with the variance? 
Could it be the factor 1/(n-1), because when I look at the code that's the main difference with the variance.

**Comment by zarquon42b** [comment]
It is completely off, no common denominator. PCs are also different:

Here is some example data:

Correct:
 Model Variance:
   eigenvalue        exVar    cumVar
1 15.75306656 0.4414717955 0.4414718
2 10.84060549 0.3038025361 0.7452743
3  4.99492113 0.1399801614 0.8852545
4  2.50372987 0.0701657749 0.9554203
5  0.85172167 0.0238690729 0.9792893
6  0.57023716 0.0159806107 0.9952700
7  0.15232495 0.0042688305 0.9995388
8  0.01645767 0.0004612181 1.0000000



Wrong:

1  1322.498246 0.3461283584 0.3461284
2   934.411535 0.2445570960 0.5906855
3   472.599725 0.1236902715 0.7143757
4   275.795438 0.0721820407 0.7865578
5   145.286522 0.0380248408 0.8245826
6   123.049157 0.0322048085 0.8567874
7    90.034014 0.0235639826 0.8803514
8    79.300447 0.0207547599 0.9011062
9    59.862128 0.0156673025 0.9167735
10   58.382954 0.0152801685 0.9320536
11   50.227784 0.0131457721 0.9451994
12   37.980172 0.0099402890 0.9551397
13   34.940589 0.0091447598 0.9642845
14   29.555829 0.0077354435 0.9720199
15   25.923225 0.0067847071 0.9788046
16   20.450436 0.0053523518 0.9841570
17   17.204953 0.0045029338 0.9886599
18   15.287786 0.0040011668 0.9926611
19    8.266268 0.0021634734 0.9948245
20    6.983840 0.0018278324 0.9966524
21    4.681258 0.0012251933 0.9978776
22    4.507966 0.0011798389 0.9990574
23    2.369963 0.0006202742 0.9996777
24    1.231586 0.0003223346 1.0000000


first 5 rows of  fist 2 PCs

Correct:
            [,1]        [,2]
[1,]  0.359203876 -0.14865107
[2,] -0.004883521 -0.01864753
[3,] -0.004952727  0.13761534
[4,]  0.386490198 -0.15307949
[5,] -0.010276152  0.03222653
[6,] -0.072823345 -0.17786145


Wrong:
              [,1]         [,2]
[1,]  0.0404137038 -0.016724603
[2,] -0.0005494363 -0.002098013
[3,] -0.0005572393  0.015482961
[4,]  0.0434836522 -0.017222822
[5,] -0.0011561577  0.003625764
[6,] -0.0081932815 -0.020011026

**Comment by tom-albrecht** [comment]
OK. Very strange indeed. Can you confirm with a debugger that you are indeed in that `else ` case?

**Comment by zarquon42b** [comment]
On 16/03/16 16:01, tom-albrecht wrote:
>
> OK. Very strange indeed. Can you confirm with a debugger that you are
> indeed in that |else| case?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/statismo/statismo/issues/239#issuecomment-197370907>
>
yes, I am.

**Comment by tom-albrecht** [comment]
It's a bit tedious, but can you check in both versions of the code, if the same data matrix X0 arrives in that `else `clause?

**Comment by zarquon42b** [comment]
On 16/03/16 16:05, tom-albrecht wrote:
>
> It's a bit tedious, but can you check in both versions of the code, if
> the same data matrix X0 arrives in that |else|clause?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/statismo/statismo/issues/239#issuecomment-197372926>
>
I got the issue to get the right values:

MatrixType Cov = X0.transpose() * X0 * 1.0/(n-1); // the /n-1 was missing
 SVDType SVD(Cov, Eigen::ComputeThinU);

Still getting weird PCS

**Comment by zarquon42b** [comment]
On 16/03/16 16:05, tom-albrecht wrote:
>
> It's a bit tedious, but can you check in both versions of the code, if
> the same data matrix X0 arrives in that |else|clause?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/statismo/statismo/issues/239#issuecomment-197372926>
>
OK ,got it

//pcaBasis /= sqrt(n - 1.0); this step is not necessary

**Comment by tom-albrecht** [comment]
Hold on, that may not be the issue. When I look at the changes, I _moved _the division by the number of samples from one line to the other. That should not explain your completely off values.

**Comment by zarquon42b** [comment]
On 16/03/16 16:10, tom-albrecht wrote:
>
> Hold on, that may not be the issue. When I look at the changes, I
> _moved _the division by the number of samples from one line to the
> other. That should not explain your completely off values.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/statismo/statismo/issues/239#issuecomment-197375396>
>
Actually now, everything works fine.

**Comment by tom-albrecht** [comment]
I now remember the reason why I moved it:
If you write it like this: `X0.transpose() * X0 * 1.0/(n-1)`,
Eigen creates a temporary matrix for `X0.transpose() * X0` in memory, which it then multiplies by `1/(n-1)`.

**Comment by tom-albrecht** [comment]
`pcaBasis /= sqrt(n - 1.0);` does not create a temporary matrix.

**Comment by tom-albrecht** [comment]
It cannot really be fine. That constant factor should only reflect in a constant factor in your variance.

**Comment by tom-albrecht** [comment]
It's all linear.

**Comment by zarquon42b** [comment]
but why implementing it in the sparse case (n > p)?

**Comment by zarquon42b** [comment]
I checked the results against a native R-function that does the same thing (actually my statismo testing)

**Comment by tom-albrecht** [comment]
What do you mean by "implementing it"?
There are two separate issues here:

1. Memory optimization
2. Incorrect computation

They should be independent.

**Comment by zarquon42b** [comment]
in the case n <p there is still 
MatrixType Cov = X0 * X0.transpose() * 1.0/(n-1);

**Comment by tom-albrecht** [comment]
We should be able to get the right result without carelessly creating temporary copies that may blow up our memory.
If both n and p are large, we still want to be memory-efficient.

**Comment by tom-albrecht** [comment]
If we get the wrong result with the memory-efficient version, there is a **bug** somewhere, but that should not be a reason to use memory-inefficient code.

**Comment by tom-albrecht** [comment]
But we are already _a lot_ further. If you use the version with `X0.transpose() * X0 * 1.0/(n-1)`, everything is fine? Can you confirm that? 
Then there must be some kind of error with the 1.0/(n-1)

**Comment by zarquon42b** [comment]
yes, with X0.transpose() * X0 * 1.0/(n-1) and skipping the pcaBasis divide everything is correct

**Comment by tom-albrecht** [comment]
OK, I will check with pencil and paper where the mistake may be.

**Comment by zarquon42b** [comment]
Yor are scaling the wrong thing: 
singularValues /= (n - 1.0);
and removing pcaBasis /= sqrt(n - 1.0);

fixes all

**Comment by tom-albrecht** [comment]
Haha, that's exactly what I just computed on my paper.

**Comment by tom-albrecht** [comment]
Sorry about that bug. In the other case, after all the calculations, the pcaBasis _did _need to be scaled, but to my embarrassment I seem to have changed the n > p case just by editing similar lines of code instead of recomputing everything on paper.

**Comment by tom-albrecht** [comment]
Can you check in the fix and send me a pull request?
It would be really cool if you could also write a unit test.
I think I wrote one for the n < p case.

**Comment by zarquon42b** [comment]
Absolutely no problem. Thanks for the optimization anyway ;)

**Comment by tom-albrecht** [comment]
https://github.com/statismo/statismo/blob/develop/modules/VTK/tests/PosteriorModelBuilderTest.cxx
I think that is the unit test.
So it would be really cool if you could do the same for the n > p case.

**Comment by tom-albrecht** [comment]
Also, there is the same mistake in the `SelfAdjointEigenSolver` case. You can add the same fix in the same pull request.

**Comment by zarquon42b** [comment]
OK, I will do the pull request for the bug fix first, and then look for adequate data and write the test.

**Comment by zarquon42b** [comment]
Fixed by #240
