### ISSUE TITLE
Warning! ***HDF5 library version mismatched error***

### ISSUE THREAD

**Issue by RuslanKosarev** [statismo/statismo#248]
I builded Statismo as superbuild and after run the command

%dir%/statismo-build-gp-model.exe -r surfaces/VSD001_femur_r.vtk -k gaussian -s 50 -p 50 -n 200 output/gaussmodel.h5

I get the error message

Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.8.13, library is 1.8.15

**Comment by zarquon42b** [comment]
This is because ITK compiles its own hdf5 library, but the command line tools accesses the one system's library path. Simply run export HDF5_DISABLE_VERSION_CHECK=1 before calling the command line tool or write it to your .bashrc

**Comment by RuslanKosarev** [comment]
Now, I build Statismo in Windows. How it can be avoided without the use of an environment variable?

**Comment by zarquon42b** [comment]
Sorry, I am not familiar with windows. Do you have another version of hdf5 installed?

**Comment by marcelluethi** [comment]
There must be another version of hdf5 somewhere in your path, which is used during runtime. 
I don't think this is a problem of statismo, or that there is even the possibility that we can prevent that from happening. I will therefore close this issue. 

Silencing that warning message is ugly, but usually works without problems.
