### ISSUE TITLE
statismo-fit-surface: the order of scales does not match to the optimized variables 

### ISSUE THREAD

**Issue by RuslanKosarev** [statismo/statismo#249]
I perform the following commands from CLI 

%dir%/statismo-build-gp-model.exe -r surfaces/VSD001_femur_r.vtk -k gaussian -s 50 -p 50 -n 10 gaussmodel.h5
%dir%/statismo-fit-surface.exe -v 2.0 -i gaussmodel.h5 -t surfaces/VSD001_femur_r.vtk -w 0.1 -p -o VSD001_femur_r.vtk

Parameter values are provided as an example. 
The current issue refers to the statismo-fit-surface. First we define transform 

https://github.com/statismo/statismo/blob/master/modules/ITK/cli/statismo-fit-image.cxx#L242
```
typedef itk::CompositeTransform<double, Dimensions> CompositeTransformType;
CompositeTransformType::Pointer pCompositeTransform = CompositeTransformType::New();
pCompositeTransform->AddTransform(pRotationAndTranslationTransform);
pCompositeTransform->AddTransform(pModelTransform);
pCompositeTransform->SetAllTransformsToOptimizeOn();
```
Second we define scales

https://github.com/statismo/statismo/blob/master/modules/ITK/cli/utils/statismo-fitting-utils.h#L213
```
typename OptimizerType::ScalesType scales(uTotalNumberOfOptimizationParameters);
for (unsigned i = 0; i < uNumberOfModelComponents; ++i) {
            scales[i] = 1.0 / (dModelParamScale);
}
for (unsigned i = uNumberOfModelComponents; i < uNumberOfModelComponents + uNrOfRotationComponents; ++i) {
            scales[i] = 1.0 / (dRotationScale);
}
for (unsigned i = uNumberOfModelComponents + uNrOfRotationComponents; i < uTotalNumberOfOptimizationParameters; ++i) {
            scales[i] = 1.0 / (dTranslationScale);
}
pOptimizer->SetScales(scales);
```
I mean, the order of variables in the array scales does not match to the order of optimized variables that returned by pOptimizer->GetCurrentPosition().

I may make pull request to fix this misunderstanding.

**Comment by marcelluethi** [comment]
Thanks for pointing this out. A PR would be awesome.
