### ISSUE TITLE
Statismo-fit-surface

### ISSUE THREAD

**Issue by nanguanuan** [statismo/statismo#256]
Hello everyone，
I really want to know whether "Model fitting" can be used to achieve segmentation？
If I use the established shape model to fit the target object with other unnecessary tissues, can other unnecessary tissue be removed by model fitting?

**Comment by marcelluethi** [comment]
Hi, 

As mentioned in my last mail, you should use the mailing list for this purpose. In case it did not work to subscribe to the mailing list, it could be because you did not use a valid e-mail address. I do not accept randomly generated email addresses. 

Best regards, 

Marcel
