### ISSUE TITLE
Can the vtkimagedata data type be used as a training sample?

### ISSUE THREAD

**Issue by nanguanuan** [statismo/statismo#257]
Hi,everyone,
Now,i see the data type including "2D STRUCTURED_POINTS"--hand_dfs example,"2D polydata points"--hand_polydata example,so i want to know that if the data type"3D STRUCTURED_POINTS "can be used sa a training sample?
Thank you very much!

**Comment by marcelluethi** [comment]
Hi, 

The short answer is yes. But may I ask you to repost your question to the statismo mailing list, together with the information if you are using VTK or ITK? 

We try to keep all the questions on the mailing list. In this way the answers remain document and the community benefits most from it. Github Issues are reserved for bugs and enhancements.
