### ISSUE TITLE
Wrong URL for HDF5

### ISSUE THREAD

**Issue by zgoey** [statismo/statismo#260]
In statismo/superbuild/External-HDF5.cmake, I had to change line 6 to make things work:
URL http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.13/src/hdf5-1.8.13.tar.gz ->
URL http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.13/src/hdf5-1.8.13.tar.gz

**Comment by marcelluethi** [comment]
Thanks for letting us know. It is now corrected in master.
