### ISSUE TITLE
Building Statismo on Windows 10 using Visual Studio Professional 2013 with update 5.

### ISSUE THREAD

**Issue by idhamari** [statismo/statismo#262]
Just to confirm that I tried the master branch and it does not work even with superbuild. 
 I used statismo-vs2015 branch and it works using the superbuild. It also works without superbuild (using external vtk and itk that use hdf5  I build from source) 
Maybe it is better to add notice about this branch for future users.

**Comment by marcelluethi** [comment]
Thanks for pointing this out. 

Unfortunately, statismo is currently not actively developed and we are also struggling to perform the basic maintenance tasks.  Anyhow, I think the VS2015 branch is sufficiently stable and a much better default than the current master branch. I will make a few more tests tonight and if everything works I will merge VS2015 into master.

**Comment by marcelluethi** [comment]
I just merged the VS2015 branch to master.
