### ISSUE TITLE
call for your help about your given femur example 

### ISSUE THREAD

**Issue by ZhiqiZhao** [statismo/statismo#273]
In your given femur example , How do you keep the points number of all femur meshes consistent? they are all 171380 points, or  what method did you use to generate femur mesh data? For your landmark constraints, how do you choose the corresponding landmarks? manually or other methods? I'm looking forward to your reply!

**Comment by marcelluethi** [comment]
As this is a question and not an issue, I will close this issue and answer the question in a separate e-mail. 
Please ask questions at statismo@googlegroups.com
