### ISSUE TITLE
Repeated CLI calls to "statismo-sample" yields identical samples

### ISSUE THREAD

**Issue by 0todd0000** [statismo/statismo#274]
I'm trying to use the Command Line Interface for **statismo-sample** to generate random samples, but it appears that the identical geometry is generated each time.

Following the documentation, I can manually generate random samples by randomly selecting parameters:

```
statismo-sample -p 1:1 4:0.1 9:2.5 -i model.h5 sample.vtk
```

However, this is a bit of a hassle.  Is there an easier way to get **statismo-sample** to generate (different) random samples on subsequent calls?

**Comment by marcelluethi** [comment]
Have you tried to use our model viewer?
https://github.com/statismo/statismo/wiki/Statismo%20Viewer

As this is a question and not an issue, I will close this issue. Please feel free to ask any further question on statismo-users@googlegroups.com.

**Comment by 0todd0000** [comment]
Yes, I have tried the model viewer, but I believe it is an issue because of the claimed functionality of the command-line tool **statismo-sample**:

> statismo-sample is used to draw samples from a model. It's possible to draw different samples such as the mean, a random sample or a sample with given parameters.

from:
https://github.com/statismo/statismo/wiki/cli-statismo-sample

This description implies that the CLI can be used to draw a random sample. This issue claims that there is a problem with the claimed functionality is non-existent, or at least that the claimed functionality is insufficiently documented. An added description like this:

"The only way to draw random samples is to generate random parameters yourself using third-party software".

then it would be clear how to generate random samples.

Please clarify whether this is indeed the only way that the CLI **statismo-sample** can be used to draw unique random samples, or if there are other command line options (e.g. a random seed) to generate unique, random samples.

**Comment by marcelluethi** [comment]
Sorry, I initially misunderstood your question.

You can draw a random sample using
> statismo-sample -i model.h5 sample.vtk
But there is currently no way to set the seed from the command line. Hence you would get different samples whenever you call statismo-sample. 

Currently the only way to generate random samples with a fixed seed is the way you describe. Even from C++ you would have this issue, as the random number generator is currently not properly seeded. 
(see the method generateNormalVector:
https://github.com/statismo/statismo/blob/master/modules/core/include/StatismoUtils.h)

Unfortunately I currently do not have the resources to work on it. But a fix does not seem difficult in case you are willing to submit a PR.

**Comment by 0todd0000** [comment]
OK, thank you very much for confirming.

I found a way around this issue:
Use the PCA basis and variance from the HDF5 file to construct the samples myself using arbitrary PC weights.  The HDF5 organization was easy to understand, thank you so much for excellent documentation!

Todd
