### ISSUE TITLE
Point Set Registration - Example

### ISSUE THREAD

**Issue by skn123** [statismo/statismo#275]
I was wondering if there is a simple example (in C++) to do the following: 
a.) Two point sets A & B without any correspondence
b.) Compute the transformation using statismo 
c.) Apply the transformation to other points from where set B was acquired (if A is assumed to be the reference point set).

Points can be in any format (ITK, VTK etc.,)

**Comment by marcelluethi** [comment]
You can check out this example:

https://github.com/statismo/statismo/blob/master/modules/ITK/examples/itkShapeModelFitting.cxx

We use the issue tracker of statismo for issues only. Please post questions about statismo on the mailing list: statismo-users@googlegroups.com.
