### ISSUE TITLE
Statismo Viewer: Download link broken

### ISSUE THREAD

**Issue by zarquon42b** [statismo/statismo#278]
Hi everyone,
unfortunately, the links to the precompiled versions of the statismo viewer are broken. 
Best
Stefan

**Comment by marcelluethi** [comment]
Hi Stefan, 

Thanks for reporting this. We recently migrated to a new server and it seems some things got lost on the way. 

I fixed the link. You should be able to download it now from here:
https://github.com/statismo/statismo/wiki/Statismo-Viewer

Best, 
Marcel

**Comment by zarquon42b** [comment]
Hi Marcel, 
thanks a lot for this. 
Greetings to Basel
Stefan
