### ISSUE TITLE
Statismo cmake installation fails due to moved VTK repo URL

### ISSUE THREAD

**Issue by dfsp-spirit** [statismo/statismo#280]
When trying to build statismo with cmake under MacOS:

```
git clone https://github.com/statismo/statismo.git
mkdir build && cd build
cmake ../statismo/superbuild 
make ## make a coffee or go for lunch
````
...the final `make` step fails with:

```
Scanning dependencies of target VTK
[ 22%] Creating directories for 'VTK'
[ 25%] Performing download step (git clone) for 'VTK'
Cloning into 'VTK'...
fatal: unable to connect to vtk.org:
vtk.org[0: 66.194.253.19]: errno=Operation timed out

Cloning into 'VTK'...
fatal: unable to connect to vtk.org:
vtk.org[0: 66.194.253.19]: errno=Operation timed out

Cloning into 'VTK'...
fatal: unable to connect to vtk.org:
vtk.org[0: 66.194.253.19]: errno=Operation timed out

-- Had to git clone more than once:
          3 times.
CMake Error at VTK-prefix/tmp/VTK-gitclone.cmake:66 (message):
  Failed to clone repository: 'git://vtk.org/VTK.git'
```

Full error log here: https://pastebin.com/Y8u4DD4y

I think the reason is that the URL for the VTK git repo has changed.

**Comment by marcelluethi** [comment]
Thanks for letting us know about this issue. Did you find already a solution for this issue (e.g. using the correct URL)

At the current moment we don't have the resources to maintain statismo much, but will keep merging PRs and help on the mailing list if people experience problem. In case you have the solution, it would be great if you could share it with other people. You may also try this fork: https://github.com/kenavolic/statismo , which should be actively developed.

**Comment by dfsp-spirit** [comment]
Thanks for your reply. 

The error originates from line 24 in /superbuild/External-VTK.cmake, which sets:

```
GIT_REPOSITORY ${git_protocol}://vtk.org/VTK.git
```

I checked the vtk website for the new repo URL. It works (i.e., compiles) if you replace that line with:

```
GIT_REPOSITORY ${git_protocol}://gitlab.kitware.com/vtk/vtk
```

**Comment by dfsp-spirit** [comment]
Forget about this. The original URL does also work if I use `https`. It seems the firewall of our institute is blocking the git protocol, which is used by default. Closing.
